using System.Text;

using static Macaron.Union.UnionCaseGenerationModelHelper;
using static Macaron.Union.UnionCaseStorageKind;

namespace Macaron.Union;

internal sealed class TaggedUnionSourceWriter(UnionGenerationModel model)
{
    #region Constants
    private const string Indent = "    ";
    #endregion

    #region Fields

    private readonly StringBuilder _builder = new();
    private string _leadingWhitespace = "";
    #endregion

    #region Methods
    public string Generate()
    {
        // header
        AppendLine("// <auto-generated />");
        AppendLine("#nullable enable");
        AppendLine();

        // namespace begin
        var hasNamespace = model.Namespace.Length > 0;

        if (hasNamespace)
        {
            AppendLine($"namespace {model.Namespace}");
            AppendLine("{");

            IncreaseIndent();
        }

        // containing types begin
        foreach (var typeString in model.ContainingTypes)
        {
            AppendLine(typeString);
            AppendLine("{");

            IncreaseIndent();
        }

        // partial declaration begin
        WritePartialDeclaration(model.TypeName);
        AppendLine("{");

        IncreaseIndent();

        // types
        if (model.Cases.Any(context => context.StorageKind == Unmanaged))
        {
            AppendLine("#region Types");
            WriteUnmanagedTypeDeclaration();
            AppendLine("#endregion");
            AppendLine();
        }

        // operator overloads
        WriteOperatorOverloads();
        AppendLine();

        // conversion operators
        WriteConversionOperators();
        AppendLine();

        // fields
        WriteFields();
        AppendLine();

        // constructors
        WriteConstructors();
        AppendLine();

        // properties
        WriteProperties();
        AppendLine();

        // equatable interface
        WriteEquatableInterface();
        AppendLine();

        // overrides
        WriteOverrides();
        AppendLine();

        // methods
        WriteMethods();

        // partial declaration end
        DecreaseIndent();

        AppendLine("}");

        // containing types end
        for (var i = 0; i < model.ContainingTypes.Length; ++i)
        {
            DecreaseIndent();

            AppendLine("}");
        }

        // namespace end
        if (hasNamespace)
        {
            DecreaseIndent();

            AppendLine("}");
        }

        return _builder.ToString();
    }

    private void WriteUnmanagedTypeDeclaration()
    {
        AppendLine("[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit)]");
        AppendLine("private struct Unmanaged");
        AppendLine("{");

        foreach (var context1 in model.Cases)
        {
            if (context1.StorageKind != Unmanaged)
            {
                continue;
            }

            AppendLine($"{Indent}[global::System.Runtime.InteropServices.FieldOffset(0)] public {context1.FullyQualifiedTypeName} Value{context1.Tag};");
        }

        AppendLine("}");
    }

    private void WritePartialDeclaration(string unionTypeName)
    {
        if (model.SupportsOfficialUnion)
        {
            AppendLine("[global::System.Runtime.CompilerServices.Union]");
            AppendLine($"partial struct {unionTypeName} : global::System.IEquatable<{unionTypeName}>, global::System.Runtime.CompilerServices.IUnion");

            return;
        }

        AppendLine($"partial struct {unionTypeName} : global::System.IEquatable<{unionTypeName}>");
    }

    private void WriteOperatorOverloads()
    {
        var typeName = model.TypeName;

        AppendLine("#region Operator Overloads");
        AppendLine($"public static bool operator ==({typeName} left, {typeName} right)");
        AppendLine("{");
        AppendLine($"{Indent}return left.Equals(right);");
        AppendLine("}");
        AppendLine();
        AppendLine($"public static bool operator !=({typeName} left, {typeName} right)");
        AppendLine("{");
        AppendLine($"{Indent}return !left.Equals(right);");
        AppendLine("}");
        AppendLine("#endregion");
    }

    private void WriteConversionOperators()
    {
        var typeName = model.TypeName;
        var caseContexts = model
            .Cases
            .Where(x => x.SupportsConversionOperators)
            .ToArray();

        AppendLine("#region Conversion Operators");

        for (var i = 0; i < caseContexts.Length; i++)
        {
            var caseContext = caseContexts[i];
            var caseTypeName = caseContext.FullyQualifiedTypeName;

            // implicit
            AppendLine($"public static implicit operator {typeName}({caseTypeName} value)");
            AppendLine("{");
            AppendLine($"{Indent}return new {typeName}(value);");
            AppendLine("}");
            AppendLine();

            // explicit
            var nullableAnnotation = caseContext.StorageKind == Reference ? "?" : "";

            AppendLine($"public static explicit operator {caseTypeName}({typeName} value)");
            AppendLine("{");
            AppendLine($"{Indent}if (value.TryGetValue(out {caseTypeName}{nullableAnnotation} result))");
            AppendLine($"{Indent}{{");
            AppendLine($"{Indent}{Indent}return result;");
            AppendLine($"{Indent}}}");
            AppendLine();
            AppendLine($"{Indent}throw new global::System.InvalidCastException($\"Unable to cast object of type '{{typeof({typeName})}}' to type '{{typeof({caseTypeName})}}'.\");");
            AppendLine("}");

            if (i < caseContexts.Length - 1)
            {
                AppendLine();
            }
        }

        AppendLine("#endregion");
    }

    private void WriteFields()
    {
        var caseContexts = model.Cases;

        AppendLine("#region Fields");
        AppendLine("private readonly byte _tag;");

        if (caseContexts.Any(x => x.StorageKind == Reference))
        {
            AppendLine("private readonly object? _reference;");
        }

        if (caseContexts.Any(x => x.StorageKind == Unmanaged))
        {
            AppendLine("private readonly Unmanaged _unmanaged;");
        }

        foreach (var context in caseContexts.Where(x => x.StorageKind == Managed))
        {
            AppendLine($"private readonly {context.FullyQualifiedTypeName} _value{context.Tag};");
        }

        AppendLine("#endregion");
    }

    private void WriteConstructors()
    {
        var typeName = model.TypeName;
        var caseContexts = model.Cases;

        AppendLine("#region Constructors");

        for (var i = 0; i < caseContexts.Length; i++)
        {
            var caseContext = caseContexts[i];
            var storageKind = caseContext.StorageKind;
            var tag = caseContext.Tag;

            AppendLine($"public {typeName}({caseContext.FullyQualifiedTypeName} value)");
            AppendLine("{");

            if (storageKind == Reference)
            {
                AppendLine($"{Indent}if ((object?)value == null)");
                AppendLine($"{Indent}{{");
                AppendLine($"{Indent}{Indent}throw new global::System.ArgumentNullException(nameof(value));");
                AppendLine($"{Indent}}}");
                AppendLine();
            }

            AppendLine($"{Indent}_tag = {tag};");
            AppendLine($"{Indent}{GetValueAccessorString(caseContext)} = value;");

            AppendLine("}");

            if (i < caseContexts.Length - 1)
            {
                AppendLine();
            }
        }

        AppendLine("#endregion");
    }

    private void WriteProperties()
    {
        AppendLine("#region Properties");
        AppendLine("public bool HasValue => _tag != 0;");
        AppendLine();
        AppendLine("public object? Value => _tag switch");
        AppendLine("{");
        AppendLine($"{Indent}0 => null,");

        foreach (var caseContext in model.Cases)
        {
            AppendLine($"{Indent}{caseContext.Tag} => {GetValueAccessorString(caseContext)},");
        }

        AppendLine($"{Indent}_ => throw new global::System.InvalidOperationException($\"Invalid tag: {{_tag}}\"),");
        AppendLine("};");
        AppendLine("#endregion");
    }

    private void WriteEquatableInterface()
    {
        var typeName = model.TypeName;

        AppendLine($"#region IEquatable<{typeName}> Interface");
        AppendLine($"public bool Equals({typeName} other)");
        AppendLine("{");
        AppendLine($"{Indent}if (_tag != other._tag)");
        AppendLine($"{Indent}{{");
        AppendLine($"{Indent}{Indent}return false;");
        AppendLine($"{Indent}}}");
        AppendLine();
        AppendLine($"{Indent}return _tag switch");
        AppendLine($"{Indent}{{");
        AppendLine($"{Indent}{Indent}0 => true,");

        foreach (var caseContext in model.Cases)
        {
            AppendLine(GetComparisonExpression(caseContext));
        }

        AppendLine($"{Indent}{Indent}_ => throw new global::System.InvalidOperationException($\"Invalid tag: {{_tag}}\"),");
        AppendLine($"{Indent}}};");
        AppendLine("}");
        AppendLine("#endregion");

        #region Local Functions
        static string GetComparisonExpression(UnionCaseGenerationModel model)
        {
            var tag = model.Tag;
            var caseTypeName = model.FullyQualifiedTypeName;
            var nullForgivingAnnotation = model.StorageKind == Reference ? "!" : "";
            var castString = model.StorageKind == Reference ? $"({caseTypeName})" : "";
            var getValueString = $"{GetValueAccessorString(model)}{nullForgivingAnnotation}";

            return $"{Indent}{Indent}{tag} => global::System.Collections.Generic.EqualityComparer<{caseTypeName}>.Default.Equals({castString}{getValueString}, {castString}other.{getValueString}),";
        }
        #endregion
    }

    private void WriteOverrides()
    {
        var typeName = model.TypeName;

        AppendLine("#region Overrides");

        // Equals
        AppendLine("public override bool Equals(object? obj)");
        AppendLine("{");
        AppendLine($"{Indent}return obj is {typeName} other && Equals(other);");
        AppendLine("}");
        AppendLine();

        // GetHashCode
        AppendLine("public override int GetHashCode()");
        AppendLine("{");
        AppendLine($"{Indent}return _tag switch");
        AppendLine($"{Indent}{{");
        AppendLine($"{Indent}{Indent}0 => 0,");

        foreach (var caseContext in model.Cases)
        {
            AppendLine($"{Indent}{Indent}{caseContext.Tag} => global::System.HashCode.Combine(_tag, {GetValueAccessorString(caseContext)}),");
        }

        AppendLine($"{Indent}{Indent}_ => throw new global::System.InvalidOperationException($\"Invalid tag: {{_tag}}\"),");
        AppendLine($"{Indent}}};");
        AppendLine("}");
        AppendLine();

        // ToString
        AppendLine("public override string ToString()");
        AppendLine("{");
        AppendLine($"{Indent}return _tag switch");
        AppendLine($"{Indent}{{");
        AppendLine($"{Indent}{Indent}0 => \"<Uninitialized>\",");

        foreach (var caseContext in model.Cases)
        {
            AppendLine($"{Indent}{Indent}{caseContext.Tag} => $\"{{{GetValueAccessorString(caseContext)}}}\",");
        }

        AppendLine($"{Indent}{Indent}_ => throw new global::System.InvalidOperationException($\"Invalid tag: {{_tag}}\"),");
        AppendLine($"{Indent}}};");
        AppendLine("}");

        AppendLine("#endregion");
    }

    private void WriteMethods()
    {
        AppendLine("#region Methods");

        // TryGet
        foreach (var caseContext in model.Cases)
        {
            var tag = caseContext.Tag;
            var caseTypeName = caseContext.FullyQualifiedTypeName;
            var notNullWhenAnnotationString = caseContext.StorageKind == Reference
                ? "[global::System.Diagnostics.CodeAnalysis.NotNullWhen(returnValue: true)] "
                : "";
            var nullableAnnotation = caseContext.StorageKind == Reference ? "?" : "";
            var castString = caseContext.StorageKind == Reference ? $"({caseTypeName})" : "";
            var nullForgivingAnnotation = caseContext.StorageKind == Reference ? "!" : "";

            AppendLine($"public bool TryGetValue({notNullWhenAnnotationString}out {caseTypeName}{nullableAnnotation} value)");
            AppendLine("{");
            AppendLine($"{Indent}if (_tag != {tag})");
            AppendLine($"{Indent}{{");
            AppendLine($"{Indent}{Indent}value = default;");
            AppendLine();
            AppendLine($"{Indent}{Indent}return false;");
            AppendLine($"{Indent}}}");
            AppendLine($"{Indent}else");
            AppendLine($"{Indent}{{");
            AppendLine($"{Indent}{Indent}value = {castString}{GetValueAccessorString(caseContext)}{nullForgivingAnnotation};");
            AppendLine();
            AppendLine($"{Indent}{Indent}return true;");
            AppendLine($"{Indent}}}");

            AppendLine("}");
            AppendLine();
        }

        // Switch
        AppendLine("public void Switch(");

        for (var i = 0; i < model.Cases.Length; i++)
        {
            var caseContext = model.Cases[i];
            var separator = i < model.Cases.Length - 1 ? "," : "";

            AppendLine($"{Indent}global::System.Action<{caseContext.FullyQualifiedTypeName}> {caseContext.ParamName}{separator}");
        }

        AppendLine(")");
        AppendLine("{");
        AppendLine($"{Indent}switch (_tag)");
        AppendLine($"{Indent}{{");
        AppendLine($"{Indent}{Indent}case 0: throw new global::System.InvalidOperationException(\"Value not initialized.\");");

        foreach (var caseContext in model.Cases)
        {
            var tag = caseContext.Tag;
            var caseTypeName = caseContext.FullyQualifiedTypeName;
            var paramName = caseContext.ParamName;
            var castString = caseContext.StorageKind == Reference ? $"({caseTypeName})" : "";
            var nullForgivingAnnotation = caseContext.StorageKind == Reference ? "!" : "";

            AppendLine($"{Indent}{Indent}case {tag}: {paramName}({castString}{GetValueAccessorString(caseContext)}{nullForgivingAnnotation}); return;");
        }

        AppendLine($"{Indent}{Indent}default: throw new global::System.InvalidOperationException($\"Invalid tag: {{_tag}}\");");
        AppendLine($"{Indent}}}");
        AppendLine("}");
        AppendLine();

        // Match
        AppendLine("public TResult Match<TResult>(");

        for (var i = 0; i < model.Cases.Length; i++)
        {
            var caseContext = model.Cases[i];
            var separator = i < model.Cases.Length - 1 ? "," : "";

            AppendLine($"{Indent}global::System.Func<{caseContext.FullyQualifiedTypeName}, TResult> {caseContext.ParamName}{separator}");
        }

        AppendLine(")");
        AppendLine("{");
        AppendLine($"{Indent}return _tag switch");
        AppendLine($"{Indent}{{");
        AppendLine($"{Indent}{Indent}0 => throw new global::System.InvalidOperationException(\"Value not initialized.\"),");

        foreach (var caseContext in model.Cases)
        {
            var caseTypeName = caseContext.FullyQualifiedTypeName;
            var paramName = caseContext.ParamName;
            var castString = caseContext.StorageKind == Reference ? $"({caseTypeName})" : "";
            var nullForgivingAnnotation = caseContext.StorageKind == Reference ? "!" : "";

            AppendLine($"{Indent}{Indent}{caseContext.Tag} => {paramName}({castString}{GetValueAccessorString(caseContext)}{nullForgivingAnnotation}),");
        }

        AppendLine($"{Indent}{Indent}_ => throw new global::System.InvalidOperationException($\"Invalid tag: {{_tag}}\"),");
        AppendLine($"{Indent}}};");
        AppendLine("}");

        AppendLine("#endregion");
    }

    private void AppendLine(string text = "")
    {
        if (text.Length > 0)
        {
            _builder.Append(_leadingWhitespace);
            _builder.AppendLine(text);
        }
        else
        {
            _builder.AppendLine("");
        }
    }

    private void IncreaseIndent()
    {
        _leadingWhitespace += Indent;
    }

    private void DecreaseIndent()
    {
        _leadingWhitespace = _leadingWhitespace[..^Indent.Length];
    }
    #endregion
}
