using System.Text;

using static Macaron.Union.TypeDeclarationHelper;
using static Macaron.Union.UnionCaseGenerationModelHelper;
using static Macaron.Union.UnionCaseStorageKind;

namespace Macaron.Union;

internal sealed class TaggedUnionJsonSerializerSourceWriter(UnionGenerationModel model)
{
    #region Constants
    private const string Indent = "    ";
    #endregion

    #region Fields

    private readonly StringBuilder _builder = new();
    private string _leadingWhitespace = "";
    #endregion

    #region Methods
    public string Generate()
    {
        // header
        AppendLine("// <auto-generated />");
        AppendLine("#nullable enable");
        AppendLine();

        // namespace begin
        var hasNamespace = model.Namespace.Length > 0;

        if (hasNamespace)
        {
            AppendLine($"namespace {model.Namespace}");
            AppendLine("{");

            IncreaseIndent();
        }

        // containing types begin
        foreach (var typeString in model.ContainingTypes)
        {
            AppendLine(typeString);
            AppendLine("{");

            IncreaseIndent();
        }

        // partial declaration begin
        var unionTypeName = model.TypeName;

        AppendLine($"[global::System.Text.Json.Serialization.JsonConverter(typeof({unionTypeName}.JsonConverter))]");
        AppendLine($"partial struct {unionTypeName}");
        AppendLine("{");

        IncreaseIndent();

        // json converter begin
        AppendLine($"private sealed class JsonConverter : global::System.Text.Json.Serialization.JsonConverter<{unionTypeName}>");
        AppendLine("{");

        IncreaseIndent();

        WriteOverrides();

        // json converter end
        DecreaseIndent();

        AppendLine("}");

        // partial declaration end
        DecreaseIndent();

        AppendLine("}");

        // containing types end
        for (var i = 0; i < model.ContainingTypes.Length; ++i)
        {
            DecreaseIndent();

            AppendLine("}");
        }

        // namespace end
        if (hasNamespace)
        {
            DecreaseIndent();

            AppendLine("}");
        }

        return _builder.ToString();
    }

    private void WriteOverrides()
    {
        var unionTypeName = model.TypeName;

        AppendLine($"#region Overrides");
        AppendLine("public override bool HandleNull => true;");
        AppendLine();
        WriteReadMethod();
        AppendLine();
        WriteWriteMethod();
        AppendLine("#endregion");
    }

    private void WriteReadMethod()
    {
        var unionTypeName = model.TypeName;

        AppendLine($"public override {unionTypeName} Read(");
        AppendLine($"{Indent}ref global::System.Text.Json.Utf8JsonReader reader,");
        AppendLine($"{Indent}global::System.Type typeToConvert,");
        AppendLine($"{Indent}global::System.Text.Json.JsonSerializerOptions options");
        AppendLine(")");
        AppendLine("{");
        AppendLine($"{Indent}if (reader.TokenType == global::System.Text.Json.JsonTokenType.Null)");
        AppendLine($"{Indent}{{");
        AppendLine($"{Indent}{Indent}return default;");
        AppendLine($"{Indent}}}");
        AppendLine();
        AppendLine($"{Indent}if (reader.TokenType != global::System.Text.Json.JsonTokenType.StartArray)");
        AppendLine($"{Indent}{{");
        AppendLine($"{Indent}{Indent}throw new global::System.Text.Json.JsonException(\"Expected a JSON array containing a tag and value.\");");
        AppendLine($"{Indent}}}");
        AppendLine();
        AppendLine($"{Indent}if (!reader.Read()");
        AppendLine($"{Indent}{Indent}|| reader.TokenType != global::System.Text.Json.JsonTokenType.Number");
        AppendLine($"{Indent}{Indent}|| !reader.TryGetByte(out var tag)");
        AppendLine($"{Indent})");
        AppendLine($"{Indent}{{");
        AppendLine($"{Indent}{Indent}throw new global::System.Text.Json.JsonException(\"Expected a byte tag as the first array element.\");");
        AppendLine($"{Indent}}}");
        AppendLine();
        AppendLine($"{Indent}if (!reader.Read() || reader.TokenType == global::System.Text.Json.JsonTokenType.EndArray)");
        AppendLine($"{Indent}{{");
        AppendLine($"{Indent}{Indent}throw new global::System.Text.Json.JsonException(\"Expected a value as the second array element.\");");
        AppendLine($"{Indent}}}");
        AppendLine();
        AppendLine($"{Indent}var result = tag switch");
        AppendLine($"{Indent}{{");

        foreach (var caseContext in model.Cases)
        {
            AppendLine($"{Indent}{Indent}{caseContext.Tag} => new {unionTypeName}({GetDeserializeExpression(caseContext)}),");
        }

        AppendLine($"{Indent}{Indent}_ => throw new global::System.Text.Json.JsonException($\"Invalid tag: {{tag}}\"),");
        AppendLine($"{Indent}}};");
        AppendLine();
        AppendLine($"{Indent}if (!reader.Read() || reader.TokenType != global::System.Text.Json.JsonTokenType.EndArray)");
        AppendLine($"{Indent}{{");
        AppendLine($"{Indent}{Indent}throw new global::System.Text.Json.JsonException(\"Expected the array to contain exactly two elements.\");");
        AppendLine($"{Indent}}}");
        AppendLine();
        AppendLine($"{Indent}return result;");
        AppendLine("}");

        #region Local Functions
        static string GetDeserializeExpression(UnionCaseGenerationModel model)
        {
            var expression = $"global::System.Text.Json.JsonSerializer.Deserialize<{model.FullyQualifiedTypeName}>(ref reader, options)";

            return model.StorageKind == Reference
                ? $"{expression} ?? throw new global::System.Text.Json.JsonException(\"The value for tag {model.Tag} cannot be null.\")"
                : expression;
        }
        #endregion
    }

    private void WriteWriteMethod()
    {
        var unionTypeName = model.TypeName;

        AppendLine("public override void Write(");
        AppendLine($"{Indent}global::System.Text.Json.Utf8JsonWriter writer,");
        AppendLine($"{Indent}{unionTypeName} value,");
        AppendLine($"{Indent}global::System.Text.Json.JsonSerializerOptions options");
        AppendLine(")");
        AppendLine("{");
        AppendLine($"{Indent}if (value._tag == 0)");
        AppendLine($"{Indent}{{");
        AppendLine($"{Indent}{Indent}writer.WriteNullValue();");
        AppendLine();
        AppendLine($"{Indent}{Indent}return;");
        AppendLine($"{Indent}}}");
        AppendLine();
        AppendLine($"{Indent}writer.WriteStartArray();");
        AppendLine($"{Indent}writer.WriteNumberValue(value._tag);");
        AppendLine();
        AppendLine($"{Indent}switch (value._tag)");
        AppendLine($"{Indent}{{");

        foreach (var caseContext in model.Cases)
        {
            AppendLine($"{Indent}{Indent}case {caseContext.Tag}: global::System.Text.Json.JsonSerializer.Serialize<{caseContext.FullyQualifiedTypeName}>(writer, {GetSerializeValueExpression(caseContext)}, options); break;");
        }

        AppendLine($"{Indent}{Indent}default: throw new global::System.Text.Json.JsonException($\"Invalid tag: {{value._tag}}\");");

        AppendLine($"{Indent}}}");
        AppendLine();
        AppendLine($"{Indent}writer.WriteEndArray();");
        AppendLine("}");

        #region Local Functions
        static string GetSerializeValueExpression(UnionCaseGenerationModel model)
        {
            var accessor = $"value.{GetValueAccessorString(model)}";

            return model.StorageKind == Reference
                ? $"({model.FullyQualifiedTypeName}){accessor}!"
                : accessor;
        }
        #endregion
    }

    private void AppendLine(string text = "")
    {
        if (text.Length > 0)
        {
            _builder.Append(_leadingWhitespace);
            _builder.AppendLine(text);
        }
        else
        {
            _builder.AppendLine("");
        }
    }

    private void IncreaseIndent()
    {
        _leadingWhitespace += Indent;
    }

    private void DecreaseIndent()
    {
        _leadingWhitespace = _leadingWhitespace[..^Indent.Length];
    }
    #endregion
}
