using static Macaron.Union.Tests.Helper;

namespace Macaron.Union.Tests;

[TestFixture]
public sealed class SourceGenerationTests
{
    [Test]
    public void ReferenceCaseTypes()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.Union.Tests;

            public class Qux<T>
            {
            }

            [TaggedUnion(typeof(Qux<int>), typeof(string))]
            public readonly partial struct Foo
            {
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.Union.Tests
            {
                partial struct Foo : global::System.IEquatable<Foo>
                {
                    #region Operator Overloads
                    public static bool operator ==(Foo left, Foo right)
                    {
                        return left.Equals(right);
                    }

                    public static bool operator !=(Foo left, Foo right)
                    {
                        return !left.Equals(right);
                    }
                    #endregion

                    #region Conversion Operators
                    public static implicit operator Foo(global::Macaron.Union.Tests.Qux<int> value)
                    {
                        return new Foo(value);
                    }

                    public static explicit operator global::Macaron.Union.Tests.Qux<int>(Foo value)
                    {
                        if (value.TryGetValue(out global::Macaron.Union.Tests.Qux<int>? result))
                        {
                            return result;
                        }

                        throw new global::System.InvalidCastException($"Unable to cast object of type '{typeof(Foo)}' to type '{typeof(global::Macaron.Union.Tests.Qux<int>)}'.");
                    }

                    public static implicit operator Foo(string value)
                    {
                        return new Foo(value);
                    }

                    public static explicit operator string(Foo value)
                    {
                        if (value.TryGetValue(out string? result))
                        {
                            return result;
                        }

                        throw new global::System.InvalidCastException($"Unable to cast object of type '{typeof(Foo)}' to type '{typeof(string)}'.");
                    }
                    #endregion

                    #region Fields
                    private readonly byte _tag;
                    private readonly object? _reference;
                    #endregion

                    #region Constructors
                    public Foo(global::Macaron.Union.Tests.Qux<int> value)
                    {
                        if ((object?)value == null)
                        {
                            throw new global::System.ArgumentNullException(nameof(value));
                        }

                        _tag = 1;
                        _reference = value;
                    }

                    public Foo(string value)
                    {
                        if ((object?)value == null)
                        {
                            throw new global::System.ArgumentNullException(nameof(value));
                        }

                        _tag = 2;
                        _reference = value;
                    }
                    #endregion

                    #region Properties
                    public bool HasValue => _tag != 0;

                    public object? Value => _tag switch
                    {
                        0 => null,
                        1 => _reference,
                        2 => _reference,
                        _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                    };
                    #endregion

                    #region IEquatable<Foo> Interface
                    public bool Equals(Foo other)
                    {
                        if (_tag != other._tag)
                        {
                            return false;
                        }

                        return _tag switch
                        {
                            0 => true,
                            1 => global::System.Collections.Generic.EqualityComparer<global::Macaron.Union.Tests.Qux<int>>.Default.Equals((global::Macaron.Union.Tests.Qux<int>)_reference!, (global::Macaron.Union.Tests.Qux<int>)other._reference!),
                            2 => global::System.Collections.Generic.EqualityComparer<string>.Default.Equals((string)_reference!, (string)other._reference!),
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }
                    #endregion

                    #region Overrides
                    public override bool Equals(object? obj)
                    {
                        return obj is Foo other && Equals(other);
                    }

                    public override int GetHashCode()
                    {
                        return _tag switch
                        {
                            0 => 0,
                            1 => global::System.HashCode.Combine(_tag, _reference),
                            2 => global::System.HashCode.Combine(_tag, _reference),
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }

                    public override string ToString()
                    {
                        return _tag switch
                        {
                            0 => "<Uninitialized>",
                            1 => $"{_reference}",
                            2 => $"{_reference}",
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }
                    #endregion

                    #region Methods
                    public bool TryGetValue([global::System.Diagnostics.CodeAnalysis.NotNullWhen(returnValue: true)] out global::Macaron.Union.Tests.Qux<int>? value)
                    {
                        if (_tag != 1)
                        {
                            value = default;

                            return false;
                        }
                        else
                        {
                            value = (global::Macaron.Union.Tests.Qux<int>)_reference!;

                            return true;
                        }
                    }

                    public bool TryGetValue([global::System.Diagnostics.CodeAnalysis.NotNullWhen(returnValue: true)] out string? value)
                    {
                        if (_tag != 2)
                        {
                            value = default;

                            return false;
                        }
                        else
                        {
                            value = (string)_reference!;

                            return true;
                        }
                    }

                    public void Switch(
                        global::System.Action<global::Macaron.Union.Tests.Qux<int>> qux,
                        global::System.Action<string> @string
                    )
                    {
                        switch (_tag)
                        {
                            case 0: throw new global::System.InvalidOperationException("Value not initialized.");
                            case 1: qux((global::Macaron.Union.Tests.Qux<int>)_reference!); return;
                            case 2: @string((string)_reference!); return;
                            default: throw new global::System.InvalidOperationException($"Invalid tag: {_tag}");
                        }
                    }

                    public TResult Match<TResult>(
                        global::System.Func<global::Macaron.Union.Tests.Qux<int>, TResult> qux,
                        global::System.Func<string, TResult> @string
                    )
                    {
                        return _tag switch
                        {
                            0 => throw new global::System.InvalidOperationException("Value not initialized."),
                            1 => qux((global::Macaron.Union.Tests.Qux<int>)_reference!),
                            2 => @string((string)_reference!),
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void UnmanagedCaseTypes()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace global::Macaron.Union.Tests;

            public readonly struct Qux
            {
                public readonly int Value;
            }

            [TaggedUnion(typeof(Qux), typeof(int))]
            public readonly partial struct Foo
            {
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.Union.Tests
            {
                partial struct Foo : global::System.IEquatable<Foo>
                {
                    #region Types
                    [global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit)]
                    private struct Unmanaged
                    {
                        [global::System.Runtime.InteropServices.FieldOffset(0)] public global::Macaron.Union.Tests.Qux Value1;
                        [global::System.Runtime.InteropServices.FieldOffset(0)] public int Value2;
                    }
                    #endregion

                    #region Operator Overloads
                    public static bool operator ==(Foo left, Foo right)
                    {
                        return left.Equals(right);
                    }

                    public static bool operator !=(Foo left, Foo right)
                    {
                        return !left.Equals(right);
                    }
                    #endregion

                    #region Conversion Operators
                    public static implicit operator Foo(global::Macaron.Union.Tests.Qux value)
                    {
                        return new Foo(value);
                    }

                    public static explicit operator global::Macaron.Union.Tests.Qux(Foo value)
                    {
                        if (value.TryGetValue(out global::Macaron.Union.Tests.Qux result))
                        {
                            return result;
                        }

                        throw new global::System.InvalidCastException($"Unable to cast object of type '{typeof(Foo)}' to type '{typeof(global::Macaron.Union.Tests.Qux)}'.");
                    }

                    public static implicit operator Foo(int value)
                    {
                        return new Foo(value);
                    }

                    public static explicit operator int(Foo value)
                    {
                        if (value.TryGetValue(out int result))
                        {
                            return result;
                        }

                        throw new global::System.InvalidCastException($"Unable to cast object of type '{typeof(Foo)}' to type '{typeof(int)}'.");
                    }
                    #endregion

                    #region Fields
                    private readonly byte _tag;
                    private readonly Unmanaged _unmanaged;
                    #endregion

                    #region Constructors
                    public Foo(global::Macaron.Union.Tests.Qux value)
                    {
                        _tag = 1;
                        _unmanaged.Value1 = value;
                    }

                    public Foo(int value)
                    {
                        _tag = 2;
                        _unmanaged.Value2 = value;
                    }
                    #endregion

                    #region Properties
                    public bool HasValue => _tag != 0;

                    public object? Value => _tag switch
                    {
                        0 => null,
                        1 => _unmanaged.Value1,
                        2 => _unmanaged.Value2,
                        _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                    };
                    #endregion

                    #region IEquatable<Foo> Interface
                    public bool Equals(Foo other)
                    {
                        if (_tag != other._tag)
                        {
                            return false;
                        }

                        return _tag switch
                        {
                            0 => true,
                            1 => global::System.Collections.Generic.EqualityComparer<global::Macaron.Union.Tests.Qux>.Default.Equals(_unmanaged.Value1, other._unmanaged.Value1),
                            2 => global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(_unmanaged.Value2, other._unmanaged.Value2),
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }
                    #endregion

                    #region Overrides
                    public override bool Equals(object? obj)
                    {
                        return obj is Foo other && Equals(other);
                    }

                    public override int GetHashCode()
                    {
                        return _tag switch
                        {
                            0 => 0,
                            1 => global::System.HashCode.Combine(_tag, _unmanaged.Value1),
                            2 => global::System.HashCode.Combine(_tag, _unmanaged.Value2),
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }

                    public override string ToString()
                    {
                        return _tag switch
                        {
                            0 => "<Uninitialized>",
                            1 => $"{_unmanaged.Value1}",
                            2 => $"{_unmanaged.Value2}",
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }
                    #endregion

                    #region Methods
                    public bool TryGetValue(out global::Macaron.Union.Tests.Qux value)
                    {
                        if (_tag != 1)
                        {
                            value = default;

                            return false;
                        }
                        else
                        {
                            value = _unmanaged.Value1;

                            return true;
                        }
                    }

                    public bool TryGetValue(out int value)
                    {
                        if (_tag != 2)
                        {
                            value = default;

                            return false;
                        }
                        else
                        {
                            value = _unmanaged.Value2;

                            return true;
                        }
                    }

                    public void Switch(
                        global::System.Action<global::Macaron.Union.Tests.Qux> qux,
                        global::System.Action<int> @int
                    )
                    {
                        switch (_tag)
                        {
                            case 0: throw new global::System.InvalidOperationException("Value not initialized.");
                            case 1: qux(_unmanaged.Value1); return;
                            case 2: @int(_unmanaged.Value2); return;
                            default: throw new global::System.InvalidOperationException($"Invalid tag: {_tag}");
                        }
                    }

                    public TResult Match<TResult>(
                        global::System.Func<global::Macaron.Union.Tests.Qux, TResult> qux,
                        global::System.Func<int, TResult> @int
                    )
                    {
                        return _tag switch
                        {
                            0 => throw new global::System.InvalidOperationException("Value not initialized."),
                            1 => qux(_unmanaged.Value1),
                            2 => @int(_unmanaged.Value2),
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void CaseAttributeOverridesCaseParameterName()
    {
        AssertGeneratedCodeContains(
            sourceCode:
            """
            namespace Macaron.Union.Tests;

            public class Qux<T>
            {
            }

            [TaggedUnion(typeof(Qux<int>), typeof(string))]
            [TaggedUnionCase(typeof(Qux<int>), "baz")]
            public readonly partial struct Foo
            {
            }
            """,
            expectedFragments:
            [
                "global::System.Action<global::Macaron.Union.Tests.Qux<int>> baz",
                "global::System.Func<global::Macaron.Union.Tests.Qux<int>, TResult> baz"
            ]
        );
    }

    [Test]
    public void InterfaceCaseParameterNameRemovesLeadingI()
    {
        AssertGeneratedCodeContains(
            sourceCode:
            """
            namespace Macaron.Union.Tests;

            public interface IQux
            {
            }

            [TaggedUnion(typeof(IQux), typeof(string))]
            public readonly partial struct Foo
            {
            }
            """,
            expectedFragments:
            [
                "global::System.Action<global::Macaron.Union.Tests.IQux> qux",
                "global::System.Func<global::Macaron.Union.Tests.IQux, TResult> qux"
            ]
        );
    }

    [Test]
    public void NullableCaseParameterNameRemovesNullableAnnotation()
    {
        AssertGeneratedCodeContains(
            sourceCode:
            """
            namespace Macaron.Union.Tests;

            [TaggedUnion(typeof(int?[]), typeof(string))]
            public readonly partial struct Foo
            {
            }
            """,
            expectedFragments:
            [
                "global::System.Action<int?[]> intArray",
                "global::System.Func<int?[], TResult> intArray"
            ]
        );
    }
}
