using static Macaron.Union.Tests.Helper;

namespace Macaron.Union.Tests;

[TestFixture]
public sealed class SourceGenerationTests
{
    [Test]
    public void HintNameIsStable()
    {
        var (_, _, generatedHintNames, _) = CompileAndGetResults<TaggedUnionGenerator>(
            sourceCode:
            """
            namespace Macaron.Union.Tests;

            [TaggedUnion(typeof(int), typeof(string))]
            public readonly partial struct Foo
            {
            }
            """,
            additionalAssemblies: [typeof(TaggedUnionAttribute).Assembly]
        );

        Assert.That(generatedHintNames, Has.Length.EqualTo(1));
        Assert.That(generatedHintNames[0], Is.EqualTo("Foo_0.c82fa166.g.cs"));
    }

    [Test]
    public void ReferenceCaseTypes()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.Union.Tests;

            public class Qux<T>
            {
            }

            [TaggedUnion(typeof(Qux<int>), typeof(string), GenerateConversionOperators = true)]
            public readonly partial struct Foo
            {
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.Union.Tests
            {
                partial struct Foo : global::System.IEquatable<Foo>
                {
                    #region Operator Overloads
                    public static bool operator ==(Foo left, Foo right)
                    {
                        return left.Equals(right);
                    }

                    public static bool operator !=(Foo left, Foo right)
                    {
                        return !left.Equals(right);
                    }
                    #endregion

                    #region Conversion Operators
                    public static implicit operator Foo(global::Macaron.Union.Tests.Qux<int> value)
                    {
                        return new Foo(value);
                    }

                    public static explicit operator global::Macaron.Union.Tests.Qux<int>(Foo value)
                    {
                        if (value.TryGetValue(out global::Macaron.Union.Tests.Qux<int>? result))
                        {
                            return result;
                        }

                        throw new global::System.InvalidCastException($"Unable to cast object of type '{typeof(Foo)}' to type '{typeof(global::Macaron.Union.Tests.Qux<int>)}'.");
                    }

                    public static implicit operator Foo(string value)
                    {
                        return new Foo(value);
                    }

                    public static explicit operator string(Foo value)
                    {
                        if (value.TryGetValue(out string? result))
                        {
                            return result;
                        }

                        throw new global::System.InvalidCastException($"Unable to cast object of type '{typeof(Foo)}' to type '{typeof(string)}'.");
                    }
                    #endregion

                    #region Fields
                    private readonly byte _tag;
                    private readonly object? _reference;
                    #endregion

                    #region Constructors
                    public Foo(global::Macaron.Union.Tests.Qux<int> value)
                    {
                        if ((object?)value == null)
                        {
                            throw new global::System.ArgumentNullException(nameof(value));
                        }

                        _tag = 1;
                        _reference = value;
                    }

                    public Foo(string value)
                    {
                        if ((object?)value == null)
                        {
                            throw new global::System.ArgumentNullException(nameof(value));
                        }

                        _tag = 2;
                        _reference = value;
                    }
                    #endregion

                    #region Properties
                    public bool HasValue => _tag != 0;

                    public object? Value => _tag switch
                    {
                        0 => null,
                        1 => _reference,
                        2 => _reference,
                        _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                    };
                    #endregion

                    #region IEquatable<Foo> Interface
                    public bool Equals(Foo other)
                    {
                        if (_tag != other._tag)
                        {
                            return false;
                        }

                        return _tag switch
                        {
                            0 => true,
                            1 => global::System.Collections.Generic.EqualityComparer<global::Macaron.Union.Tests.Qux<int>>.Default.Equals((global::Macaron.Union.Tests.Qux<int>)_reference!, (global::Macaron.Union.Tests.Qux<int>)other._reference!),
                            2 => global::System.Collections.Generic.EqualityComparer<string>.Default.Equals((string)_reference!, (string)other._reference!),
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }
                    #endregion

                    #region Overrides
                    public override bool Equals(object? obj)
                    {
                        return obj is Foo other && Equals(other);
                    }

                    public override int GetHashCode()
                    {
                        return _tag switch
                        {
                            0 => 0,
                            1 => global::System.HashCode.Combine(_tag, _reference),
                            2 => global::System.HashCode.Combine(_tag, _reference),
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }

                    public override string ToString()
                    {
                        return _tag switch
                        {
                            0 => "<Uninitialized>",
                            1 => $"{_reference}",
                            2 => $"{_reference}",
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }
                    #endregion

                    #region Methods
                    public bool TryGetValue([global::System.Diagnostics.CodeAnalysis.NotNullWhen(returnValue: true)] out global::Macaron.Union.Tests.Qux<int>? value)
                    {
                        if (_tag != 1)
                        {
                            value = default;

                            return false;
                        }
                        else
                        {
                            value = (global::Macaron.Union.Tests.Qux<int>)_reference!;

                            return true;
                        }
                    }

                    public bool TryGetValue([global::System.Diagnostics.CodeAnalysis.NotNullWhen(returnValue: true)] out string? value)
                    {
                        if (_tag != 2)
                        {
                            value = default;

                            return false;
                        }
                        else
                        {
                            value = (string)_reference!;

                            return true;
                        }
                    }

                    public void Switch(
                        global::System.Action<global::Macaron.Union.Tests.Qux<int>> qux,
                        global::System.Action<string> @string
                    )
                    {
                        switch (_tag)
                        {
                            case 0: throw new global::System.InvalidOperationException("Value not initialized.");
                            case 1: qux((global::Macaron.Union.Tests.Qux<int>)_reference!); return;
                            case 2: @string((string)_reference!); return;
                            default: throw new global::System.InvalidOperationException($"Invalid tag: {_tag}");
                        }
                    }

                    public TResult Match<TResult>(
                        global::System.Func<global::Macaron.Union.Tests.Qux<int>, TResult> qux,
                        global::System.Func<string, TResult> @string
                    )
                    {
                        return _tag switch
                        {
                            0 => throw new global::System.InvalidOperationException("Value not initialized."),
                            1 => qux((global::Macaron.Union.Tests.Qux<int>)_reference!),
                            2 => @string((string)_reference!),
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void UnmanagedCaseTypes()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace global::Macaron.Union.Tests;

            public readonly struct Qux
            {
                public readonly int Value;
            }

            [TaggedUnion(typeof(Qux), typeof(int), GenerateConversionOperators = true)]
            public readonly partial struct Foo
            {
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.Union.Tests
            {
                partial struct Foo : global::System.IEquatable<Foo>
                {
                    #region Types
                    [global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit)]
                    private struct Unmanaged
                    {
                        [global::System.Runtime.InteropServices.FieldOffset(0)] public global::Macaron.Union.Tests.Qux Value1;
                        [global::System.Runtime.InteropServices.FieldOffset(0)] public int Value2;
                    }
                    #endregion

                    #region Operator Overloads
                    public static bool operator ==(Foo left, Foo right)
                    {
                        return left.Equals(right);
                    }

                    public static bool operator !=(Foo left, Foo right)
                    {
                        return !left.Equals(right);
                    }
                    #endregion

                    #region Conversion Operators
                    public static implicit operator Foo(global::Macaron.Union.Tests.Qux value)
                    {
                        return new Foo(value);
                    }

                    public static explicit operator global::Macaron.Union.Tests.Qux(Foo value)
                    {
                        if (value.TryGetValue(out global::Macaron.Union.Tests.Qux result))
                        {
                            return result;
                        }

                        throw new global::System.InvalidCastException($"Unable to cast object of type '{typeof(Foo)}' to type '{typeof(global::Macaron.Union.Tests.Qux)}'.");
                    }

                    public static implicit operator Foo(int value)
                    {
                        return new Foo(value);
                    }

                    public static explicit operator int(Foo value)
                    {
                        if (value.TryGetValue(out int result))
                        {
                            return result;
                        }

                        throw new global::System.InvalidCastException($"Unable to cast object of type '{typeof(Foo)}' to type '{typeof(int)}'.");
                    }
                    #endregion

                    #region Fields
                    private readonly byte _tag;
                    private readonly Unmanaged _unmanaged;
                    #endregion

                    #region Constructors
                    public Foo(global::Macaron.Union.Tests.Qux value)
                    {
                        _tag = 1;
                        _unmanaged.Value1 = value;
                    }

                    public Foo(int value)
                    {
                        _tag = 2;
                        _unmanaged.Value2 = value;
                    }
                    #endregion

                    #region Properties
                    public bool HasValue => _tag != 0;

                    public object? Value => _tag switch
                    {
                        0 => null,
                        1 => _unmanaged.Value1,
                        2 => _unmanaged.Value2,
                        _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                    };
                    #endregion

                    #region IEquatable<Foo> Interface
                    public bool Equals(Foo other)
                    {
                        if (_tag != other._tag)
                        {
                            return false;
                        }

                        return _tag switch
                        {
                            0 => true,
                            1 => global::System.Collections.Generic.EqualityComparer<global::Macaron.Union.Tests.Qux>.Default.Equals(_unmanaged.Value1, other._unmanaged.Value1),
                            2 => global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(_unmanaged.Value2, other._unmanaged.Value2),
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }
                    #endregion

                    #region Overrides
                    public override bool Equals(object? obj)
                    {
                        return obj is Foo other && Equals(other);
                    }

                    public override int GetHashCode()
                    {
                        return _tag switch
                        {
                            0 => 0,
                            1 => global::System.HashCode.Combine(_tag, _unmanaged.Value1),
                            2 => global::System.HashCode.Combine(_tag, _unmanaged.Value2),
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }

                    public override string ToString()
                    {
                        return _tag switch
                        {
                            0 => "<Uninitialized>",
                            1 => $"{_unmanaged.Value1}",
                            2 => $"{_unmanaged.Value2}",
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }
                    #endregion

                    #region Methods
                    public bool TryGetValue(out global::Macaron.Union.Tests.Qux value)
                    {
                        if (_tag != 1)
                        {
                            value = default;

                            return false;
                        }
                        else
                        {
                            value = _unmanaged.Value1;

                            return true;
                        }
                    }

                    public bool TryGetValue(out int value)
                    {
                        if (_tag != 2)
                        {
                            value = default;

                            return false;
                        }
                        else
                        {
                            value = _unmanaged.Value2;

                            return true;
                        }
                    }

                    public void Switch(
                        global::System.Action<global::Macaron.Union.Tests.Qux> qux,
                        global::System.Action<int> @int
                    )
                    {
                        switch (_tag)
                        {
                            case 0: throw new global::System.InvalidOperationException("Value not initialized.");
                            case 1: qux(_unmanaged.Value1); return;
                            case 2: @int(_unmanaged.Value2); return;
                            default: throw new global::System.InvalidOperationException($"Invalid tag: {_tag}");
                        }
                    }

                    public TResult Match<TResult>(
                        global::System.Func<global::Macaron.Union.Tests.Qux, TResult> qux,
                        global::System.Func<int, TResult> @int
                    )
                    {
                        return _tag switch
                        {
                            0 => throw new global::System.InvalidOperationException("Value not initialized."),
                            1 => qux(_unmanaged.Value1),
                            2 => @int(_unmanaged.Value2),
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void ManagedCaseTypes()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.Union.Tests;

            public readonly struct Baz
            {
                public readonly object Value;
            }

            public readonly struct Bar
            {
                public readonly Baz Value;
            }

            public readonly struct Qux
            {
                public readonly Baz Value;
            }

            [TaggedUnion(typeof(Qux), typeof(Bar), GenerateConversionOperators = true)]
            public readonly partial struct Foo
            {
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.Union.Tests
            {
                partial struct Foo : global::System.IEquatable<Foo>
                {
                    #region Operator Overloads
                    public static bool operator ==(Foo left, Foo right)
                    {
                        return left.Equals(right);
                    }

                    public static bool operator !=(Foo left, Foo right)
                    {
                        return !left.Equals(right);
                    }
                    #endregion

                    #region Conversion Operators
                    public static implicit operator Foo(global::Macaron.Union.Tests.Qux value)
                    {
                        return new Foo(value);
                    }

                    public static explicit operator global::Macaron.Union.Tests.Qux(Foo value)
                    {
                        if (value.TryGetValue(out global::Macaron.Union.Tests.Qux result))
                        {
                            return result;
                        }

                        throw new global::System.InvalidCastException($"Unable to cast object of type '{typeof(Foo)}' to type '{typeof(global::Macaron.Union.Tests.Qux)}'.");
                    }

                    public static implicit operator Foo(global::Macaron.Union.Tests.Bar value)
                    {
                        return new Foo(value);
                    }

                    public static explicit operator global::Macaron.Union.Tests.Bar(Foo value)
                    {
                        if (value.TryGetValue(out global::Macaron.Union.Tests.Bar result))
                        {
                            return result;
                        }

                        throw new global::System.InvalidCastException($"Unable to cast object of type '{typeof(Foo)}' to type '{typeof(global::Macaron.Union.Tests.Bar)}'.");
                    }
                    #endregion

                    #region Fields
                    private readonly byte _tag;
                    private readonly global::Macaron.Union.Tests.Qux _value1;
                    private readonly global::Macaron.Union.Tests.Bar _value2;
                    #endregion

                    #region Constructors
                    public Foo(global::Macaron.Union.Tests.Qux value)
                    {
                        _tag = 1;
                        _value1 = value;
                    }

                    public Foo(global::Macaron.Union.Tests.Bar value)
                    {
                        _tag = 2;
                        _value2 = value;
                    }
                    #endregion

                    #region Properties
                    public bool HasValue => _tag != 0;

                    public object? Value => _tag switch
                    {
                        0 => null,
                        1 => _value1,
                        2 => _value2,
                        _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                    };
                    #endregion

                    #region IEquatable<Foo> Interface
                    public bool Equals(Foo other)
                    {
                        if (_tag != other._tag)
                        {
                            return false;
                        }

                        return _tag switch
                        {
                            0 => true,
                            1 => global::System.Collections.Generic.EqualityComparer<global::Macaron.Union.Tests.Qux>.Default.Equals(_value1, other._value1),
                            2 => global::System.Collections.Generic.EqualityComparer<global::Macaron.Union.Tests.Bar>.Default.Equals(_value2, other._value2),
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }
                    #endregion

                    #region Overrides
                    public override bool Equals(object? obj)
                    {
                        return obj is Foo other && Equals(other);
                    }

                    public override int GetHashCode()
                    {
                        return _tag switch
                        {
                            0 => 0,
                            1 => global::System.HashCode.Combine(_tag, _value1),
                            2 => global::System.HashCode.Combine(_tag, _value2),
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }

                    public override string ToString()
                    {
                        return _tag switch
                        {
                            0 => "<Uninitialized>",
                            1 => $"{_value1}",
                            2 => $"{_value2}",
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }
                    #endregion

                    #region Methods
                    public bool TryGetValue(out global::Macaron.Union.Tests.Qux value)
                    {
                        if (_tag != 1)
                        {
                            value = default;

                            return false;
                        }
                        else
                        {
                            value = _value1;

                            return true;
                        }
                    }

                    public bool TryGetValue(out global::Macaron.Union.Tests.Bar value)
                    {
                        if (_tag != 2)
                        {
                            value = default;

                            return false;
                        }
                        else
                        {
                            value = _value2;

                            return true;
                        }
                    }

                    public void Switch(
                        global::System.Action<global::Macaron.Union.Tests.Qux> qux,
                        global::System.Action<global::Macaron.Union.Tests.Bar> bar
                    )
                    {
                        switch (_tag)
                        {
                            case 0: throw new global::System.InvalidOperationException("Value not initialized.");
                            case 1: qux(_value1); return;
                            case 2: bar(_value2); return;
                            default: throw new global::System.InvalidOperationException($"Invalid tag: {_tag}");
                        }
                    }

                    public TResult Match<TResult>(
                        global::System.Func<global::Macaron.Union.Tests.Qux, TResult> qux,
                        global::System.Func<global::Macaron.Union.Tests.Bar, TResult> bar
                    )
                    {
                        return _tag switch
                        {
                            0 => throw new global::System.InvalidOperationException("Value not initialized."),
                            1 => qux(_value1),
                            2 => bar(_value2),
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void ComplexCaseTypes()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.Union.Tests;

            public readonly struct Qux
            {
                public readonly int Value;
            }

            public readonly class Quux
            {
                public float Value;
            }

            public readonly struct Bar
            {
                public readonly object Value;
            }

            public readonly struct Baz
            {
                public readonly string Value;
            }

            [TaggedUnion(typeof(Qux), typeof(string), typeof(int), typeof(Bar), typeof(Quux), typeof(Baz), GenerateConversionOperators = true)]
            public readonly partial struct Foo
            {
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.Union.Tests
            {
                partial struct Foo : global::System.IEquatable<Foo>
                {
                    #region Types
                    [global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit)]
                    private struct Unmanaged
                    {
                        [global::System.Runtime.InteropServices.FieldOffset(0)] public global::Macaron.Union.Tests.Qux Value1;
                        [global::System.Runtime.InteropServices.FieldOffset(0)] public int Value3;
                    }
                    #endregion

                    #region Operator Overloads
                    public static bool operator ==(Foo left, Foo right)
                    {
                        return left.Equals(right);
                    }

                    public static bool operator !=(Foo left, Foo right)
                    {
                        return !left.Equals(right);
                    }
                    #endregion

                    #region Conversion Operators
                    public static implicit operator Foo(global::Macaron.Union.Tests.Qux value)
                    {
                        return new Foo(value);
                    }

                    public static explicit operator global::Macaron.Union.Tests.Qux(Foo value)
                    {
                        if (value.TryGetValue(out global::Macaron.Union.Tests.Qux result))
                        {
                            return result;
                        }

                        throw new global::System.InvalidCastException($"Unable to cast object of type '{typeof(Foo)}' to type '{typeof(global::Macaron.Union.Tests.Qux)}'.");
                    }

                    public static implicit operator Foo(string value)
                    {
                        return new Foo(value);
                    }

                    public static explicit operator string(Foo value)
                    {
                        if (value.TryGetValue(out string? result))
                        {
                            return result;
                        }

                        throw new global::System.InvalidCastException($"Unable to cast object of type '{typeof(Foo)}' to type '{typeof(string)}'.");
                    }

                    public static implicit operator Foo(int value)
                    {
                        return new Foo(value);
                    }

                    public static explicit operator int(Foo value)
                    {
                        if (value.TryGetValue(out int result))
                        {
                            return result;
                        }

                        throw new global::System.InvalidCastException($"Unable to cast object of type '{typeof(Foo)}' to type '{typeof(int)}'.");
                    }

                    public static implicit operator Foo(global::Macaron.Union.Tests.Bar value)
                    {
                        return new Foo(value);
                    }

                    public static explicit operator global::Macaron.Union.Tests.Bar(Foo value)
                    {
                        if (value.TryGetValue(out global::Macaron.Union.Tests.Bar result))
                        {
                            return result;
                        }

                        throw new global::System.InvalidCastException($"Unable to cast object of type '{typeof(Foo)}' to type '{typeof(global::Macaron.Union.Tests.Bar)}'.");
                    }

                    public static implicit operator Foo(global::Macaron.Union.Tests.Quux value)
                    {
                        return new Foo(value);
                    }

                    public static explicit operator global::Macaron.Union.Tests.Quux(Foo value)
                    {
                        if (value.TryGetValue(out global::Macaron.Union.Tests.Quux? result))
                        {
                            return result;
                        }

                        throw new global::System.InvalidCastException($"Unable to cast object of type '{typeof(Foo)}' to type '{typeof(global::Macaron.Union.Tests.Quux)}'.");
                    }

                    public static implicit operator Foo(global::Macaron.Union.Tests.Baz value)
                    {
                        return new Foo(value);
                    }

                    public static explicit operator global::Macaron.Union.Tests.Baz(Foo value)
                    {
                        if (value.TryGetValue(out global::Macaron.Union.Tests.Baz result))
                        {
                            return result;
                        }

                        throw new global::System.InvalidCastException($"Unable to cast object of type '{typeof(Foo)}' to type '{typeof(global::Macaron.Union.Tests.Baz)}'.");
                    }
                    #endregion

                    #region Fields
                    private readonly byte _tag;
                    private readonly object? _reference;
                    private readonly Unmanaged _unmanaged;
                    private readonly global::Macaron.Union.Tests.Bar _value4;
                    private readonly global::Macaron.Union.Tests.Baz _value6;
                    #endregion

                    #region Constructors
                    public Foo(global::Macaron.Union.Tests.Qux value)
                    {
                        _tag = 1;
                        _unmanaged.Value1 = value;
                    }

                    public Foo(string value)
                    {
                        if ((object?)value == null)
                        {
                            throw new global::System.ArgumentNullException(nameof(value));
                        }

                        _tag = 2;
                        _reference = value;
                    }

                    public Foo(int value)
                    {
                        _tag = 3;
                        _unmanaged.Value3 = value;
                    }

                    public Foo(global::Macaron.Union.Tests.Bar value)
                    {
                        _tag = 4;
                        _value4 = value;
                    }

                    public Foo(global::Macaron.Union.Tests.Quux value)
                    {
                        if ((object?)value == null)
                        {
                            throw new global::System.ArgumentNullException(nameof(value));
                        }

                        _tag = 5;
                        _reference = value;
                    }

                    public Foo(global::Macaron.Union.Tests.Baz value)
                    {
                        _tag = 6;
                        _value6 = value;
                    }
                    #endregion

                    #region Properties
                    public bool HasValue => _tag != 0;

                    public object? Value => _tag switch
                    {
                        0 => null,
                        1 => _unmanaged.Value1,
                        2 => _reference,
                        3 => _unmanaged.Value3,
                        4 => _value4,
                        5 => _reference,
                        6 => _value6,
                        _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                    };
                    #endregion

                    #region IEquatable<Foo> Interface
                    public bool Equals(Foo other)
                    {
                        if (_tag != other._tag)
                        {
                            return false;
                        }

                        return _tag switch
                        {
                            0 => true,
                            1 => global::System.Collections.Generic.EqualityComparer<global::Macaron.Union.Tests.Qux>.Default.Equals(_unmanaged.Value1, other._unmanaged.Value1),
                            2 => global::System.Collections.Generic.EqualityComparer<string>.Default.Equals((string)_reference!, (string)other._reference!),
                            3 => global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(_unmanaged.Value3, other._unmanaged.Value3),
                            4 => global::System.Collections.Generic.EqualityComparer<global::Macaron.Union.Tests.Bar>.Default.Equals(_value4, other._value4),
                            5 => global::System.Collections.Generic.EqualityComparer<global::Macaron.Union.Tests.Quux>.Default.Equals((global::Macaron.Union.Tests.Quux)_reference!, (global::Macaron.Union.Tests.Quux)other._reference!),
                            6 => global::System.Collections.Generic.EqualityComparer<global::Macaron.Union.Tests.Baz>.Default.Equals(_value6, other._value6),
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }
                    #endregion

                    #region Overrides
                    public override bool Equals(object? obj)
                    {
                        return obj is Foo other && Equals(other);
                    }

                    public override int GetHashCode()
                    {
                        return _tag switch
                        {
                            0 => 0,
                            1 => global::System.HashCode.Combine(_tag, _unmanaged.Value1),
                            2 => global::System.HashCode.Combine(_tag, _reference),
                            3 => global::System.HashCode.Combine(_tag, _unmanaged.Value3),
                            4 => global::System.HashCode.Combine(_tag, _value4),
                            5 => global::System.HashCode.Combine(_tag, _reference),
                            6 => global::System.HashCode.Combine(_tag, _value6),
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }

                    public override string ToString()
                    {
                        return _tag switch
                        {
                            0 => "<Uninitialized>",
                            1 => $"{_unmanaged.Value1}",
                            2 => $"{_reference}",
                            3 => $"{_unmanaged.Value3}",
                            4 => $"{_value4}",
                            5 => $"{_reference}",
                            6 => $"{_value6}",
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }
                    #endregion

                    #region Methods
                    public bool TryGetValue(out global::Macaron.Union.Tests.Qux value)
                    {
                        if (_tag != 1)
                        {
                            value = default;

                            return false;
                        }
                        else
                        {
                            value = _unmanaged.Value1;

                            return true;
                        }
                    }

                    public bool TryGetValue([global::System.Diagnostics.CodeAnalysis.NotNullWhen(returnValue: true)] out string? value)
                    {
                        if (_tag != 2)
                        {
                            value = default;

                            return false;
                        }
                        else
                        {
                            value = (string)_reference!;

                            return true;
                        }
                    }

                    public bool TryGetValue(out int value)
                    {
                        if (_tag != 3)
                        {
                            value = default;

                            return false;
                        }
                        else
                        {
                            value = _unmanaged.Value3;

                            return true;
                        }
                    }

                    public bool TryGetValue(out global::Macaron.Union.Tests.Bar value)
                    {
                        if (_tag != 4)
                        {
                            value = default;

                            return false;
                        }
                        else
                        {
                            value = _value4;

                            return true;
                        }
                    }

                    public bool TryGetValue([global::System.Diagnostics.CodeAnalysis.NotNullWhen(returnValue: true)] out global::Macaron.Union.Tests.Quux? value)
                    {
                        if (_tag != 5)
                        {
                            value = default;

                            return false;
                        }
                        else
                        {
                            value = (global::Macaron.Union.Tests.Quux)_reference!;

                            return true;
                        }
                    }

                    public bool TryGetValue(out global::Macaron.Union.Tests.Baz value)
                    {
                        if (_tag != 6)
                        {
                            value = default;

                            return false;
                        }
                        else
                        {
                            value = _value6;

                            return true;
                        }
                    }

                    public void Switch(
                        global::System.Action<global::Macaron.Union.Tests.Qux> qux,
                        global::System.Action<string> @string,
                        global::System.Action<int> @int,
                        global::System.Action<global::Macaron.Union.Tests.Bar> bar,
                        global::System.Action<global::Macaron.Union.Tests.Quux> quux,
                        global::System.Action<global::Macaron.Union.Tests.Baz> baz
                    )
                    {
                        switch (_tag)
                        {
                            case 0: throw new global::System.InvalidOperationException("Value not initialized.");
                            case 1: qux(_unmanaged.Value1); return;
                            case 2: @string((string)_reference!); return;
                            case 3: @int(_unmanaged.Value3); return;
                            case 4: bar(_value4); return;
                            case 5: quux((global::Macaron.Union.Tests.Quux)_reference!); return;
                            case 6: baz(_value6); return;
                            default: throw new global::System.InvalidOperationException($"Invalid tag: {_tag}");
                        }
                    }

                    public TResult Match<TResult>(
                        global::System.Func<global::Macaron.Union.Tests.Qux, TResult> qux,
                        global::System.Func<string, TResult> @string,
                        global::System.Func<int, TResult> @int,
                        global::System.Func<global::Macaron.Union.Tests.Bar, TResult> bar,
                        global::System.Func<global::Macaron.Union.Tests.Quux, TResult> quux,
                        global::System.Func<global::Macaron.Union.Tests.Baz, TResult> baz
                    )
                    {
                        return _tag switch
                        {
                            0 => throw new global::System.InvalidOperationException("Value not initialized."),
                            1 => qux(_unmanaged.Value1),
                            2 => @string((string)_reference!),
                            3 => @int(_unmanaged.Value3),
                            4 => bar(_value4),
                            5 => quux((global::Macaron.Union.Tests.Quux)_reference!),
                            6 => baz(_value6),
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void CaseAttributeOverridesCaseTag()
    {
        AssertGeneratedCodeContains(
            sourceCode:
            """
            namespace Macaron.Union.Tests;

            [TaggedUnion(typeof(int), typeof(string))]
            [TaggedUnionCase(typeof(int), tag: 42)]
            public readonly partial struct Foo
            {
            }
            """,
            expectedFragments:
            [
                "public int Value42;",
                "_tag = 42;",
                "if (_tag != 42)",
                "case 42: @int(",
                "42 => @int("
            ]
        );
    }

    [Test]
    public void CaseAttributeOverridesCaseParameterName()
    {
        AssertGeneratedCodeContains(
            sourceCode:
            """
            namespace Macaron.Union.Tests;

            public class Qux<T>
            {
            }

            [TaggedUnion(typeof(Qux<int>), typeof(string))]
            [TaggedUnionCase(typeof(Qux<int>), "baz")]
            public readonly partial struct Foo
            {
            }
            """,
            expectedFragments:
            [
                "_tag = 1;",
                "global::System.Action<global::Macaron.Union.Tests.Qux<int>> baz",
                "global::System.Func<global::Macaron.Union.Tests.Qux<int>, TResult> baz"
            ]
        );
    }

    [Test]
    public void InterfaceCaseParameterNameRemovesLeadingI()
    {
        AssertGeneratedCodeContains(
            sourceCode:
            """
            namespace Macaron.Union.Tests;

            public interface IQux
            {
            }

            [TaggedUnion(typeof(IQux), typeof(string))]
            public readonly partial struct Foo
            {
            }
            """,
            expectedFragments:
            [
                "global::System.Action<global::Macaron.Union.Tests.IQux> qux",
                "global::System.Func<global::Macaron.Union.Tests.IQux, TResult> qux"
            ]
        );
    }

    [Test]
    public void InterfaceCaseTypeDoesNotGenerateConversionOperators()
    {
        var (_, generatedCodes, _, _) = CompileAndGetResults<TaggedUnionGenerator>(
            sourceCode:
            """
            namespace Macaron.Union.Tests;

            public interface IQux
            {
            }

            [TaggedUnion(typeof(IQux), typeof(string), GenerateConversionOperators = true)]
            public readonly partial struct Foo
            {
            }
            """,
            additionalAssemblies: [typeof(TaggedUnionAttribute).Assembly]
        );
        var generatedCode = generatedCodes.Single();

        Assert.Multiple(() =>
        {
            Assert.That(
                generatedCode,
                Does.Not.Contain("implicit operator Foo(global::Macaron.Union.Tests.IQux value)")
            );
            Assert.That(
                generatedCode,
                Does.Not.Contain("explicit operator global::Macaron.Union.Tests.IQux(Foo value)")
            );
            Assert.That(generatedCode, Does.Contain("implicit operator Foo(string value)"));
            Assert.That(generatedCode, Does.Contain("explicit operator string(Foo value)"));
        });
    }

    [Test]
    public void ConversionOperatorsAreDisabledByDefault()
    {
        var (_, generatedCodes, _, _) = CompileAndGetResults<TaggedUnionGenerator>(
            sourceCode:
            """
            namespace Macaron.Union.Tests;

            [TaggedUnion(typeof(int), typeof(string))]
            public readonly partial struct Foo
            {
            }
            """,
            additionalAssemblies: [typeof(TaggedUnionAttribute).Assembly]
        );
        var generatedCode = generatedCodes.Single();

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Does.Not.Contain("#region Conversion Operators"));
            Assert.That(generatedCode, Does.Not.Contain("implicit operator"));
            Assert.That(generatedCode, Does.Not.Contain("explicit operator"));
            Assert.That(generatedCode, Does.Contain("public Foo(int value)"));
            Assert.That(generatedCode, Does.Contain("public Foo(string value)"));
        });
    }

    [Test]
    public void NullableCaseParameterNameRemovesNullableAnnotation()
    {
        AssertGeneratedCodeContains(
            sourceCode:
            """
            namespace Macaron.Union.Tests;

            [TaggedUnion(typeof(int?[]), typeof(string))]
            public readonly partial struct Foo
            {
            }
            """,
            expectedFragments:
            [
                "global::System.Action<int?[]> intArray",
                "global::System.Func<int?[], TResult> intArray"
            ]
        );
    }
}
