using static Macaron.TaggedUnion.Tests.Helper;

namespace Macaron.TaggedUnion.Tests;

[TestFixture]
public sealed class TaggedUnionTests
{
    [Test]
    public void ReferenceOnly()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.TaggedUnion.Tests;

            public class Qux<T>
            {
            }

            [TaggedUnion(typeof(Qux<int>), typeof(string))]
            public readonly partial struct Foo
            {
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.TaggedUnion.Tests
            {
                partial struct Foo : global::System.IEquatable<Foo>
                {
                    #region Operator Overloads
                    public static bool operator ==(Foo left, Foo right)
                    {
                        return left.Equals(right);
                    }

                    public static bool operator !=(Foo left, Foo right)
                    {
                        return !left.Equals(right);
                    }
                    #endregion

                    #region Conversion Operators
                    public static implicit operator Foo(global::Macaron.TaggedUnion.Tests.Qux<int> value)
                    {
                        return new Foo(value);
                    }

                    public static explicit operator global::Macaron.TaggedUnion.Tests.Qux<int>(Foo value)
                    {
                        if (value.TryGetValue(out global::Macaron.TaggedUnion.Tests.Qux<int>? result))
                        {
                            return result;
                        }

                        throw new global::System.InvalidCastException($"Unable to cast object of type '{typeof(Foo)}' to type '{typeof(global::Macaron.TaggedUnion.Tests.Qux<int>)}'.");
                    }

                    public static implicit operator Foo(string value)
                    {
                        return new Foo(value);
                    }

                    public static explicit operator string(Foo value)
                    {
                        if (value.TryGetValue(out string? result))
                        {
                            return result;
                        }

                        throw new global::System.InvalidCastException($"Unable to cast object of type '{typeof(Foo)}' to type '{typeof(string)}'.");
                    }
                    #endregion

                    #region Fields
                    private readonly byte _tag;
                    private readonly object? _reference;
                    #endregion

                    #region Constructors
                    public Foo(global::Macaron.TaggedUnion.Tests.Qux<int> value)
                    {
                        if ((object?)value == null)
                        {
                            throw new global::System.ArgumentNullException(nameof(value));
                        }

                        _tag = 1;
                        _reference = value;
                    }

                    public Foo(string value)
                    {
                        if ((object?)value == null)
                        {
                            throw new global::System.ArgumentNullException(nameof(value));
                        }

                        _tag = 2;
                        _reference = value;
                    }
                    #endregion

                    #region Properties
                    public bool HasValue => _tag != 0;

                    public object? Value => _tag switch
                    {
                        0 => null,
                        1 => _reference,
                        2 => _reference,
                        _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                    };
                    #endregion

                    #region IEquatable<Foo> Interface
                    public bool Equals(Foo other)
                    {
                        if (_tag != other._tag)
                        {
                            return false;
                        }

                        return _tag switch
                        {
                            0 => true,
                            1 => global::System.Collections.Generic.EqualityComparer<global::Macaron.TaggedUnion.Tests.Qux<int>>.Default.Equals((global::Macaron.TaggedUnion.Tests.Qux<int>)_reference!, (global::Macaron.TaggedUnion.Tests.Qux<int>)other._reference!),
                            2 => global::System.Collections.Generic.EqualityComparer<string>.Default.Equals((string)_reference!, (string)other._reference!),
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }
                    #endregion

                    #region Overrides
                    public override bool Equals(object? obj)
                    {
                        return obj is Foo other && Equals(other);
                    }

                    public override int GetHashCode()
                    {
                        return _tag switch
                        {
                            0 => 0,
                            1 => global::System.HashCode.Combine(_tag, _reference),
                            2 => global::System.HashCode.Combine(_tag, _reference),
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }

                    public override string ToString()
                    {
                        return _tag switch
                        {
                            0 => "<Uninitialized>",
                            1 => $"{_reference}",
                            2 => $"{_reference}",
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }
                    #endregion

                    #region Methods
                    public bool TryGetValue([global::System.Diagnostics.CodeAnalysis.NotNullWhen(returnValue: true)] out global::Macaron.TaggedUnion.Tests.Qux<int>? value)
                    {
                        if (_tag != 1)
                        {
                            value = default;

                            return false;
                        }
                        else
                        {
                            value = (global::Macaron.TaggedUnion.Tests.Qux<int>)_reference!;

                            return true;
                        }
                    }

                    public bool TryGetValue([global::System.Diagnostics.CodeAnalysis.NotNullWhen(returnValue: true)] out string? value)
                    {
                        if (_tag != 2)
                        {
                            value = default;

                            return false;
                        }
                        else
                        {
                            value = (string)_reference!;

                            return true;
                        }
                    }

                    public void Switch(
                        global::System.Action<global::Macaron.TaggedUnion.Tests.Qux<int>> qux,
                        global::System.Action<string> @string
                    )
                    {
                        switch (_tag)
                        {
                            case 0: throw new global::System.InvalidOperationException("Value not initialized.");
                            case 1: qux((global::Macaron.TaggedUnion.Tests.Qux<int>)_reference!); return;
                            case 2: @string((string)_reference!); return;
                            default: throw new global::System.InvalidOperationException($"Invalid tag: {_tag}");
                        }
                    }

                    public TResult Match<TResult>(
                        global::System.Func<global::Macaron.TaggedUnion.Tests.Qux<int>, TResult> qux,
                        global::System.Func<string, TResult> @string
                    )
                    {
                        return _tag switch
                        {
                            0 => throw new global::System.InvalidOperationException("Value not initialized."),
                            1 => qux((global::Macaron.TaggedUnion.Tests.Qux<int>)_reference!),
                            2 => @string((string)_reference!),
                            _ => throw new global::System.InvalidOperationException($"Invalid tag: {_tag}"),
                        };
                    }
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void TypeIsNotReadOnlyPartialStruct()
    {
        AssertDiagnostic(
            sourceCode:
            """
            namespace Macaron.TaggedUnion.Tests;

            [TaggedUnion(typeof(int), typeof(string))]
            public partial struct Foo
            {
            }
            """,
            expectedDiagnosticId: "MTU0001"
        );
    }

    [Test]
    public void TypeIsNotGeneric()
    {
        AssertDiagnostic(
            sourceCode:
            """
            namespace Macaron.TaggedUnion.Tests;

            [TaggedUnion(typeof(int), typeof(string))]
            public readonly partial struct Foo<T>
            {
            }
            """,
            expectedDiagnosticId: "MTU0002"
        );
    }
}
